# PLANTILLA CALIDAD DE DATOS

**IMPORTANTE**: Recuerda hacer una copia de esta plantilla para no machacar la original.

## IMPORTAR PAQUETES

In [1]:
import numpy as np
import pandas as pd
from janitor import clean_names

#Automcompletar rápido
%config IPCompleter.greedy=True

## IMPORTAR LOS DATOS

Sustituir la ruta del proyecto.

In [2]:
ruta_proyecto = 'C:/Users/isaac/Google Drive/DS4B/CursoMachineLearningPython/03_MACHINE_LEARNING/08_CASOS/00_PROYECTO1'

Sustituir el nombre_fichero_datos.

In [3]:
nombre_fichero_datos = 'muestra.csv'

Cargar los datos.

In [4]:
ruta_completa = ruta_proyecto + '/02_Datos/03_Trabajo/' + nombre_fichero_datos

df = pd.read_csv(ruta_completa,index_col=0)
df

,Edad,Trabajo,Estado Civil,Fomación,Impago,Prestamo hipotecario,Prestamo Personal,Canal de contacto,Mes,Dia de la semana,num contactos esta campaña,num días último contacto,num contactos otras campañas,resultado campaña anterior,variación tasa empleo,euribor3m,contrata_fondos
11773,34.0,admin.,single,university.degree,no,no,yes,cellular,aug,NaN,3,999,0,nonexistent,14,497,0
33937,29.0,admin.,single,university.degree,no,yes,no,telephone,jun,NaN,2,999,0,nonexistent,14,4961,0
24094,45.0,services,married,NaN,unknown,yes,yes,telephone,aug,NaN,2,999,0,nonexistent,14,4964,0
36175,46.0,services,married,NaN,no,yes,no,cellular,may,NaN,3,999,1,failure,-18,1313,0
4635,56.0,technician,married,professional.course,unknown,no,no,telephone,may,NaN,1,999,0,nonexistent,11,486,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28179,50.0,admin.,married,basic.6y,no,no,no,cellular,aug,NaN,1,999,0,nonexistent,14,4963,0
37547,35.0,admin.,single,high.school,no,yes,yes,cellular,may,NaN,1,999,1,failure,-18,1327,0
13461,60.0,retired,divorced,basic.4y,unknown,no,no,telephone,may,wed,2,999,0,nonexistent,11,4857,0
9873,26.0,admin.,single,high.school,no,no,no,telephone,may,NaN,2,999,0,nonexistent,11,4856,0
26917,45.0,blue-collar,divorced,basic.9y,no,yes,no,telephone,jun,NaN,3,999,0,nonexistent,14,4958,0

## CORRECCIÓN DE NOMBRES DE VARIABLES

### Corrección automática

In [5]:
df = clean_names(df)
df

,edad,trabajo,estado_civil,fomacion,impago,prestamo_hipotecario,prestamo_personal,canal_de_contacto,mes,dia_de_la_semana,num_contactos_esta_campana,num_dias_ultimo_contacto,num_contactos_otras_campanas,resultado_campana_anterior,variacion_tasa_empleo,euribor3m,contrata_fondos
11773,34.0,admin.,single,university.degree,no,no,yes,cellular,aug,NaN,3,999,0,nonexistent,14,497,0
33937,29.0,admin.,single,university.degree,no,yes,no,telephone,jun,NaN,2,999,0,nonexistent,14,4961,0
24094,45.0,services,married,NaN,unknown,yes,yes,telephone,aug,NaN,2,999,0,nonexistent,14,4964,0
36175,46.0,services,married,NaN,no,yes,no,cellular,may,NaN,3,999,1,failure,-18,1313,0
4635,56.0,technician,married,professional.course,unknown,no,no,telephone,may,NaN,1,999,0,nonexistent,11,486,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28179,50.0,admin.,married,basic.6y,no,no,no,cellular,aug,NaN,1,999,0,nonexistent,14,4963,0
37547,35.0,admin.,single,high.school,no,yes,yes,cellular,may,NaN,1,999,1,failure,-18,1327,0
13461,60.0,retired,divorced,basic.4y,unknown,no,no,telephone,may,wed,2,999,0,nonexistent,11,4857,0
9873,26.0,admin.,single,high.school,no,no,no,telephone,may,NaN,2,999,0,nonexistent,11,4856,0
26917,45.0,blue-collar,divorced,basic.9y,no,yes,no,telephone,jun,NaN,3,999,0,nonexistent,14,4958,0

### Corrección manual

In [6]:
df.rename(columns = {'fomacion':'formacion',
                     'prestamo_hipotecario':'hipoteca',
                     'prestamo_personal':'consumo'}, inplace=True)
df

,edad,trabajo,estado_civil,formacion,impago,hipoteca,consumo,canal_de_contacto,mes,dia_de_la_semana,num_contactos_esta_campana,num_dias_ultimo_contacto,num_contactos_otras_campanas,resultado_campana_anterior,variacion_tasa_empleo,euribor3m,contrata_fondos
11773,34.0,admin.,single,university.degree,no,no,yes,cellular,aug,NaN,3,999,0,nonexistent,14,497,0
33937,29.0,admin.,single,university.degree,no,yes,no,telephone,jun,NaN,2,999,0,nonexistent,14,4961,0
24094,45.0,services,married,NaN,unknown,yes,yes,telephone,aug,NaN,2,999,0,nonexistent,14,4964,0
36175,46.0,services,married,NaN,no,yes,no,cellular,may,NaN,3,999,1,failure,-18,1313,0
4635,56.0,technician,married,professional.course,unknown,no,no,telephone,may,NaN,1,999,0,nonexistent,11,486,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28179,50.0,admin.,married,basic.6y,no,no,no,cellular,aug,NaN,1,999,0,nonexistent,14,4963,0
37547,35.0,admin.,single,high.school,no,yes,yes,cellular,may,NaN,1,999,1,failure,-18,1327,0
13461,60.0,retired,divorced,basic.4y,unknown,no,no,telephone,may,wed,2,999,0,nonexistent,11,4857,0
9873,26.0,admin.,single,high.school,no,no,no,telephone,may,NaN,2,999,0,nonexistent,11,4856,0
26917,45.0,blue-collar,divorced,basic.9y,no,yes,no,telephone,jun,NaN,3,999,0,nonexistent,14,4958,0

## VISIÓN GENERAL

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 20000 entries, 11773 to 26917
Data columns (total 17 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   edad                          18613 non-null  float64
 1   trabajo                       20000 non-null  object
 2   estado_civil                  20000 non-null  object
 3   formacion                     17549 non-null  object
 4   impago                        20000 non-null  object
 5   hipoteca                      20000 non-null  object
 6   consumo                       20000 non-null  object
 7   canal_de_contacto             20000 non-null  object
 8   mes                           20000 non-null  object
 9   dia_de_la_semana              1032 non-null   object
 10  num_contactos_esta_campana    20000 non-null  int64
 11  num_dias_ultimo_contacto      20000 non-null  int64
 12  num_contactos_otras_campanas  20000 non-null  int64
 13  resultado_campana_anterior    20000 non-null  object
 14  variacion_tasa_empleo         20000 non-null  int64
 15  euribor3m                     20000 non-null  int64
 16  contrata_fondos               20000 non-null  int64
dtypes: float64(1), int64(6), object(10)
memory usage: 2.7+ MB

## TIPOS DE DATOS

### Identificación

In [8]:
df.dtypes

edad                            float64
trabajo                          object
estado_civil                     object
formacion                        object
impago                           object
hipoteca                         object
consumo                          object
canal_de_contacto                object
mes                              object
dia_de_la_semana                 object
num_contactos_esta_campana        int64
num_dias_ultimo_contacto          int64
num_contactos_otras_campanas      int64
resultado_campana_anterior       object
variacion_tasa_empleo             int64
euribor3m                         int64
contrata_fondos                   int64
dtype: object

### Corrección

In [9]:
df = df.astype({'edad':'Int64',
           'euribor3m': 'float'})

df.dtypes

edad                              Int64
trabajo                          object
estado_civil                     object
formacion                        object
impago                           object
hipoteca                         object
consumo                          object
canal_de_contacto                object
mes                              object
dia_de_la_semana                 object
num_contactos_esta_campana        int64
num_dias_ultimo_contacto          int64
num_contactos_otras_campanas      int64
resultado_campana_anterior       object
variacion_tasa_empleo             int64
euribor3m                       float64
contrata_fondos                   int64
dtype: object

## VALORES ÚNICOS

### Identificación

In [10]:
df.nunique().sort_values()

contrata_fondos                   2
canal_de_contacto                 2
impago                            3
hipoteca                          3
consumo                           3
resultado_campana_anterior        3
estado_civil                      4
dia_de_la_semana                  5
formacion                         8
num_contactos_otras_campanas      8
variacion_tasa_empleo            10
mes                              10
trabajo                          12
num_dias_ultimo_contacto         25
num_contactos_esta_campana       40
edad                             76
euribor3m                       298
dtype: int64

### Corrección

In [11]:
df.drop(columns = 'canal_de_contacto', inplace = True)

## DUPLICADOS

### Identificación

In [12]:
df.duplicated().sum()

418

### Corrección

In [13]:
df.drop_duplicates(inplace = True)

## SEPARAR NUMÉRICAS Y CATEGÓRICAS

### Categóricas

In [14]:
cat = df.select_dtypes(exclude = 'number').copy()

### Numéricas

In [15]:
num = df.select_dtypes(include='number').copy()

## GESTIÓN DE CATEGÓRICAS

### Nulos

#### Identificación

In [16]:
cat.isna().sum().sort_values(ascending = False)

dia_de_la_semana              18551
formacion                      2436
trabajo                           0
estado_civil                      0
impago                            0
hipoteca                          0
consumo                           0
mes                               0
resultado_campana_anterior        0
dtype: int64

#### Corrección

##### Eliminar la variable

In [17]:
cat.drop(columns = 'dia_de_la_semana',inplace = True)

##### Eliminar registros

*Cuidado: Si se eliminan registros hay que eliminarlos tanto de cat como de num*

In [18]:
criterio = 3
cat.dropna(thresh=criterio, inplace=True)
num.dropna(thresh=criterio, inplace=True)

##### Imputar por un valor

###### Variables a imputar

In [19]:
var_imputar_valor = ['resultado_campana_anterior','formacion']

###### Valor por el que imputar

In [20]:
valor = 'NULO'

###### Imputar

In [21]:
# cat[var_imputar_valor] = cat[var_imputar_valor].fillna(valor)

##### Imputar por la moda

###### Variables a imputar

In [22]:
var_imputar_moda = ['resultado_campana_anterior','formacion']

###### Funcion para imputar con la moda

In [23]:
def imputar_moda(variable):
    return(variable.fillna(variable.mode()[0]))

###### Imputar con la moda

In [24]:
cat[var_imputar_moda] = cat[var_imputar_moda].apply(imputar_moda)

### Atípicos

#### Categorías poco frecuentes

##### Función para agrupar categorías raras en 'OTROS'

In [25]:
def agrupar_cat_raras(variable, criterio = 0.05):
    #Calcula las frecuencias
    frecuencias = variable.value_counts(normalize=True)
    #Identifica las que están por debajo del criterio
    temp = [cada for cada in frecuencias.loc[frecuencias < criterio].index.values]
    #Las recodifica en 'OTROS'
    temp2 = np.where(variable.isin(temp),'OTROS',variable)
    #Devuelve el resultado
    return(temp2)

##### Variables a imputar

In [26]:
var_imputar_moda = ['trabajo','estado_civil']

##### Aplicar

In [27]:
for variable in var_imputar_moda:
    cat[variable] = agrupar_cat_raras(cat[variable],criterio = 0.02)

## GESTIÓN DE NUMÉRICAS

### Nulos

#### Identificación

In [28]:
num.isna().sum().sort_values(ascending = False)

edad                            1357
num_contactos_esta_campana         0
num_dias_ultimo_contacto           0
num_contactos_otras_campanas       0
variacion_tasa_empleo              0
euribor3m                          0
contrata_fondos                    0
dtype: int64

#### Corrección

##### Eliminar la variable

In [29]:
num.drop(columns = 'num_contactos_otras_campanas',inplace = True)

##### Eliminar registros

*Cuidado: Si se eliminan registros hay que eliminarlos tanto de cat como de num*

In [30]:
criterio = 3
cat.dropna(thresh=criterio, inplace=True)
num.dropna(thresh=criterio, inplace=True)

##### Imputar por la media

###### Variables a imputar

In [31]:
var_imputar_media = ['edad','num_contactos_esta_campana']

###### Funcion para imputar con la media

In [32]:
def imputar_media(variable):
    if pd.api.types.is_integer_dtype(variable):
        return(variable.fillna(int(variable.mean())))
    else:
        return(variable.fillna(variable.mean()))

###### Imputar con la media

In [33]:
#num[var_imputar_media] = num[var_imputar_media].apply(imputar_media)

##### Imputar por la mediana

###### Variables a imputar

In [34]:
var_imputar_mediana = ['edad','num_contactos_esta_campana']

###### Funcion para imputar con la mediana

In [35]:
def imputar_mediana(variable):
    if pd.api.types.is_integer_dtype(variable):
        return(variable.fillna(int(variable.median())))
    else:
        return(variable.fillna(variable.median()))

###### Imputar con la mediana

In [36]:
num[var_imputar_mediana] = num[var_imputar_mediana].apply(imputar_mediana)

### Atípicos

#### Por desviación típica

##### Identificación

###### Definir el número de desviaciones típicas

In [37]:
num_desv_tip = 4

###### Función que devuelve los índices de los atípicos

In [38]:
def atipicos_desv_tip(variable, num_desv_tip = 4):
    #sacamos los nulos por ahora
    variable = variable.dropna()
    #calculamos los límites
    media = np.mean(variable)
    sd = np.std(variable)
    umbral = sd * num_desv_tip
    lim_inf = media - umbral
    lim_sup = media + umbral
    #encontramos los índices de los que están fuera de los límites
    indices = [indice for indice,valor in variable.items() if valor < lim_inf or valor > lim_sup]
    return(indices)

###### Función que cuenta el número de atípicos

In [39]:
def conteo_atipicos(df,variable, num_desv_tip = 4):
    atipicos = atipicos_desv_tip(df[variable], num_desv_tip)
    return(df.loc[atipicos,variable].value_counts())

###### Variables a aplicar

In [40]:
var_atipicos_dt = ['edad','num_contactos_esta_campana']

###### Aplicar

In [41]:
for variable in var_atipicos_dt:
    print('\n' + variable + ':\n')
    print(conteo_atipicos(num,variable,num_desv_tip))

edad:

83    10
88     8
81     8
85     7
82     5
86     5
84     3
98     1
94     1
91     1
89     1
95     1
Name: edad, dtype: Int64

num_contactos_esta_campana:

17    32
14    32
16    24
15    17
19    13
20    12
18    11
21     9
31     6
24     6
23     6
22     5
28     4
26     4
30     3
33     2
27     2
42     2
25     2
29     2
56     1
37     1
34     1
39     1
35     1
43     1
32     1
Name: num_contactos_esta_campana, dtype: int64

##### Corrección

Eliminar los registros que tengan al menos un atípico en alguna de las variables indicadas.

*Cuidado: Si se eliminan registros hay que eliminarlos tanto de cat como de num*

###### Variables a aplicar

In [42]:
var_atipicos_dt = ['edad','num_contactos_esta_campana']

###### Aplicar

In [43]:
for variable in var_atipicos_dt:
    cat.drop(atipicos_desv_tip(num[variable], num_desv_tip),axis = 0, inplace = True)
    num.drop(atipicos_desv_tip(num[variable], num_desv_tip),axis = 0, inplace = True)

#### Por winsorización manual para una variable

##### Identificación

###### Variable a analizar

In [44]:
variable = 'variacion_tasa_empleo'

###### Comprobar el mínimo y máximo actual

In [45]:
num[variable].describe().loc[['min','max']]

min   -34.0
max    14.0
Name: variacion_tasa_empleo, dtype: float64

##### Corrección

###### Definir el mínimo y máximo tolerable.

In [46]:
minimo = -20
maximo = 10

###### Aplicar

In [47]:
num[variable].clip(minimo,maximo, inplace=True)

#### Por winsorización automática para múltiples variables

##### Variables a winsorizar.

In [48]:
var_winsorizar = ['edad','num_contactos_esta_campana']

##### Definir los percentiles mínimos y máximos.

In [49]:
p_min = 0.01
p_max = 0.99

##### Aplicar

In [50]:
# Winsorización automática para cada variable
for variable in var_winsorizar:
    print(f"Procesando la variable: {variable}")
    
    # Calcula los cuantiles para cada variable
    lower_quantile = num[variable].quantile(p_min)
    upper_quantile = num[variable].quantile(p_max)
    
    # Si la columna es de tipo Int64, redondea los cuantiles a enteros
    if pd.api.types.is_integer_dtype(num[variable]):
        lower_quantile = int(round(lower_quantile))
        upper_quantile = int(round(upper_quantile))
        print(f"Cuantiles redondeados para la variable de tipo Int64 '{variable}': {lower_quantile}, {upper_quantile}")
    else:
        print(f"Cuantiles para la variable de tipo Float '{variable}': {lower_quantile}, {upper_quantile}")
    
    # Aplica la winsorización utilizando los cuantiles como límites
    num[variable].clip(lower=lower_quantile, upper=upper_quantile, inplace=True)

    # Imprimir los resultados después de la winsorización
    print(f"Resultados después de la winsorización para la variable '{variable}':")
    print(num[variable].describe())

## GUARDAR DATASETS TRAS CALIDAD DE DATOS

Guarda los avances en df, cat y num con un sufijo para poder guardar o recuperar avances del proyecto.

En formato pickle para no perder las modificaciones de metadatos.

### Definir los nombres de los archivos

In [51]:
ruta_trabajo = ruta_proyecto + '/02_Datos/03_Trabajo/' + 'trabajo_resultado_calidad.pickle'
ruta_cat = ruta_proyecto + '/02_Datos/03_Trabajo/' + 'cat_resultado_calidad.pickle'
ruta_num = ruta_proyecto + '/02_Datos/03_Trabajo/' + 'num_resultado_calidad.pickle'

### Guardar los archivos

In [52]:
df.to_pickle(ruta_trabajo)
cat.to_pickle(ruta_cat)
num.to_pickle(ruta_num)